version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/deploy"
    schedule:
      interval: "daily"
