linters:
  enable:
    - dogsled
    - dupl
    - goconst
    - gofmt
    - gofumpt
    - golint
    - gocyclo
    - lll
    - govet
    - misspell
    - nakedret
    - unparam

issues:
  exclude-use-default: false
