before:
  hooks:
    - go mod download
env:
  - GO111MODULE=on
builds:
  - id: "scraper"
    main: ./cmd/scraper/main.go
    binary: boca-chica-bot-scraper
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - id: "publisher"
    main: ./cmd/publisher/main.go
    binary: boca-chica-bot-publisher
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archives:
  - id: scraper
    builds:
      - scraper
    format: zip
    name_template: "{{ .ProjectName }}-scraper_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: publisher
    builds:
      - publisher
    format: zip
    name_template: "{{ .ProjectName }}-publisher_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
changelog:
  skip: true
release:
  disable: true
