name: Lint Code Base

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  super-linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint
        uses: github/super-linter@v3
        env:
          # VALIDATE_ALL_CODEBASE: false
          VALIDATE_GO: false # super-linter currently not great for Go: https://github.com/github/super-linter/issues/143
          VALIDATE_TERRAFORM_TERRASCAN: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  golangci:
    name: Lint Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33


