name: release

on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      # - name: Get branch name
      #   run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Get Release Version
        uses: cycjimmy/semantic-release-action@v2
        id: semantic-dry-run
        with:
          semantic_version: 17
          # branches: |
          #   [ "master",
          #     "${{ env.BRANCH_NAME }}"
          #   ]
          dry_run: true
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ENV: $GITHUB_ENV

      - name: Set Go Version
        run: echo "GO_VERSION=$(grep "go 1." go.mod | cut -d " " -f 2)" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build Release
        if: ${{ env.NEW_RELEASE == 'true' }}
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --rm-dist --skip-validate
        env:
          GORELEASER_CURRENT_TAG: v${{ env.VERSION }}
      - name: Release
        if: ${{ env.NEW_RELEASE == 'true' }}
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17
          # branches: |
          #   [ "master",
          #     "${{ env.BRANCH_NAME }}"
          #   ]
          dry_run: true
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ENV: $GITHUB_ENV
      - name: Go Report Card
        uses: creekorful/goreportcard-action@v1.0
