name: release

on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            node_modules
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-go-
      # - name: Get branch name
      #   run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Setup Semantic-Release
        run: npm i -D @semantic-release/changelog @semantic-release/exec @semantic-release/git semantic-release@17
      - name: Get Release Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ENV: $GITHUB_ENV
        run: npx semantic-release --dry-run
        # run: npx semantic-release --dry-run --branches ${{ env.BRANCH_NAME }}
      - name: Set Go Version
        run: echo "GO_VERSION=$(grep "go 1." go.mod | cut -d " " -f 2)" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build Release
        if: ${{ env.NEW_RELEASE == 'true' }}
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: --skip-publish --rm-dist --skip-validate
        env:
          GORELEASER_CURRENT_TAG: v${{ env.VERSION }}
      - run: ls -al dist
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ENV: $GITHUB_ENV
        run: npx semantic-release@17
      - name: Go Report Card
        uses: creekorful/goreportcard-action@v1.0
