name: release

on:
  push:
    branches:
      - master
      - semantic-release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # persist-credentials: false
      - name: Version
        uses: cycjimmy/semantic-release-action@v2
        id: semantic-dry-run
        with:
          semantic_version: 17
          branches: |
            [ 'master',
              'semantic-release'
            ]
          dry_run: true
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Build
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --rm-dist
        env:
          NEXT_VERSION: ${{ steps.semantic-dry-run.outputs.new_release_version }}
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # - name: Release
      #   uses: cycjimmy/semantic-release-action@v2
      #   id: semantic
      #   with:
      #     semantic_version: 17
      #     dry_run: true
      #     extra_plugins: |
      #       @semantic-release/changelog
      #       @semantic-release/git
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Echo semantic version
      #   if: steps.semantic.outputs.new_release_published == 'true'
      #   run: |
      #     echo ${{ steps.semantic.outputs.new_release_version }}
      #     echo ${{ steps.semantic.outputs.new_release_major_version }}
      #     echo ${{ steps.semantic.outputs.new_release_minor_version }}
      #     echo ${{ steps.semantic.outputs.new_release_patch_version }}



      # - name: Go Report Card
      #   uses: creekorful/goreportcard-action@v1.0
